/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_lib/msg/NumpyArray.msg */
#ifndef HRL_LIB_MESSAGE_NUMPYARRAY_H
#define HRL_LIB_MESSAGE_NUMPYARRAY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace hrl_lib
{
template <class ContainerAllocator>
struct NumpyArray_ : public ros::Message
{
  typedef NumpyArray_<ContainerAllocator> Type;

  NumpyArray_()
  : header()
  , data()
  , shape()
  , dtype()
  {
  }

  NumpyArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , data(_alloc)
  , shape(_alloc)
  , dtype(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  data;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _shape_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  shape;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dtype_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  dtype;


  ROS_DEPRECATED uint32_t get_shape_size() const { return (uint32_t)shape.size(); }
  ROS_DEPRECATED void set_shape_size(uint32_t size) { shape.resize((size_t)size); }
  ROS_DEPRECATED void get_shape_vec(std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) const { vec = this->shape; }
  ROS_DEPRECATED void set_shape_vec(const std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) { this->shape = vec; }
private:
  static const char* __s_getDataType_() { return "hrl_lib/NumpyArray"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "18efe15e5e1ff3c15a2573bddc555f1b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
string data\n\
int32[] shape\n\
string dtype\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, data);
    ros::serialization::serialize(stream, shape);
    ros::serialization::serialize(stream, dtype);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, data);
    ros::serialization::deserialize(stream, shape);
    ros::serialization::deserialize(stream, dtype);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(data);
    size += ros::serialization::serializationLength(shape);
    size += ros::serialization::serializationLength(dtype);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_lib::NumpyArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_lib::NumpyArray_<ContainerAllocator>  const> ConstPtr;
}; // struct NumpyArray
typedef  ::hrl_lib::NumpyArray_<std::allocator<void> > NumpyArray;

typedef boost::shared_ptr< ::hrl_lib::NumpyArray> NumpyArrayPtr;
typedef boost::shared_ptr< ::hrl_lib::NumpyArray const> NumpyArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hrl_lib::NumpyArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hrl_lib::NumpyArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hrl_lib

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_lib::NumpyArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "18efe15e5e1ff3c15a2573bddc555f1b";
  }

  static const char* value(const  ::hrl_lib::NumpyArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x18efe15e5e1ff3c1ULL;
  static const uint64_t static_value2 = 0x5a2573bddc555f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_lib::NumpyArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_lib/NumpyArray";
  }

  static const char* value(const  ::hrl_lib::NumpyArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_lib::NumpyArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string data\n\
int32[] shape\n\
string dtype\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hrl_lib::NumpyArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hrl_lib::NumpyArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hrl_lib::NumpyArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_lib::NumpyArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.data);
    stream.next(m.shape);
    stream.next(m.dtype);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct NumpyArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrl_lib::NumpyArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hrl_lib::NumpyArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
    s << indent << "shape[]" << std::endl;
    for (size_t i = 0; i < v.shape.size(); ++i)
    {
      s << indent << "  shape[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.shape[i]);
    }
    s << indent << "dtype: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dtype);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HRL_LIB_MESSAGE_NUMPYARRAY_H

