/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_lib/msg/PlanarBaseVel.msg */
#ifndef HRL_LIB_MESSAGE_PLANARBASEVEL_H
#define HRL_LIB_MESSAGE_PLANARBASEVEL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace hrl_lib
{
template <class ContainerAllocator>
struct PlanarBaseVel_ : public ros::Message
{
  typedef PlanarBaseVel_<ContainerAllocator> Type;

  PlanarBaseVel_()
  : header()
  , xvel(0.0)
  , yvel(0.0)
  , angular_velocity(0.0)
  {
  }

  PlanarBaseVel_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , xvel(0.0)
  , yvel(0.0)
  , angular_velocity(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _xvel_type;
  double xvel;

  typedef double _yvel_type;
  double yvel;

  typedef double _angular_velocity_type;
  double angular_velocity;


private:
  static const char* __s_getDataType_() { return "hrl_lib/PlanarBaseVel"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "c844e0872ecf385742618d1ca7390275"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 xvel\n\
float64 yvel\n\
float64 angular_velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, xvel);
    ros::serialization::serialize(stream, yvel);
    ros::serialization::serialize(stream, angular_velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, xvel);
    ros::serialization::deserialize(stream, yvel);
    ros::serialization::deserialize(stream, angular_velocity);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(xvel);
    size += ros::serialization::serializationLength(yvel);
    size += ros::serialization::serializationLength(angular_velocity);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_lib::PlanarBaseVel_<ContainerAllocator>  const> ConstPtr;
}; // struct PlanarBaseVel
typedef  ::hrl_lib::PlanarBaseVel_<std::allocator<void> > PlanarBaseVel;

typedef boost::shared_ptr< ::hrl_lib::PlanarBaseVel> PlanarBaseVelPtr;
typedef boost::shared_ptr< ::hrl_lib::PlanarBaseVel const> PlanarBaseVelConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hrl_lib::PlanarBaseVel_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hrl_lib

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c844e0872ecf385742618d1ca7390275";
  }

  static const char* value(const  ::hrl_lib::PlanarBaseVel_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc844e0872ecf3857ULL;
  static const uint64_t static_value2 = 0x42618d1ca7390275ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_lib/PlanarBaseVel";
  }

  static const char* value(const  ::hrl_lib::PlanarBaseVel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 xvel\n\
float64 yvel\n\
float64 angular_velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hrl_lib::PlanarBaseVel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hrl_lib::PlanarBaseVel_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.xvel);
    stream.next(m.yvel);
    stream.next(m.angular_velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PlanarBaseVel_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrl_lib::PlanarBaseVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hrl_lib::PlanarBaseVel_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xvel: ";
    Printer<double>::stream(s, indent + "  ", v.xvel);
    s << indent << "yvel: ";
    Printer<double>::stream(s, indent + "  ", v.yvel);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HRL_LIB_MESSAGE_PLANARBASEVEL_H

