/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_lib/msg/Pose3DOF.msg */
#ifndef HRL_LIB_MESSAGE_POSE3DOF_H
#define HRL_LIB_MESSAGE_POSE3DOF_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace hrl_lib
{
template <class ContainerAllocator>
struct Pose3DOF_ : public ros::Message
{
  typedef Pose3DOF_<ContainerAllocator> Type;

  Pose3DOF_()
  : header()
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  , dt(0.0)
  {
  }

  Pose3DOF_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , y(0.0)
  , theta(0.0)
  , dt(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _theta_type;
  double theta;

  typedef double _dt_type;
  double dt;


private:
  static const char* __s_getDataType_() { return "hrl_lib/Pose3DOF"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "646ead44a0e6fecf4e14ca116f12b08b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64 x\n\
float64 y\n\
float64 theta\n\
float64 dt\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, theta);
    ros::serialization::serialize(stream, dt);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, theta);
    ros::serialization::deserialize(stream, dt);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(theta);
    size += ros::serialization::serializationLength(dt);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_lib::Pose3DOF_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_lib::Pose3DOF_<ContainerAllocator>  const> ConstPtr;
}; // struct Pose3DOF
typedef  ::hrl_lib::Pose3DOF_<std::allocator<void> > Pose3DOF;

typedef boost::shared_ptr< ::hrl_lib::Pose3DOF> Pose3DOFPtr;
typedef boost::shared_ptr< ::hrl_lib::Pose3DOF const> Pose3DOFConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hrl_lib::Pose3DOF_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hrl_lib::Pose3DOF_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hrl_lib

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_lib::Pose3DOF_<ContainerAllocator> > {
  static const char* value() 
  {
    return "646ead44a0e6fecf4e14ca116f12b08b";
  }

  static const char* value(const  ::hrl_lib::Pose3DOF_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x646ead44a0e6fecfULL;
  static const uint64_t static_value2 = 0x4e14ca116f12b08bULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_lib::Pose3DOF_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_lib/Pose3DOF";
  }

  static const char* value(const  ::hrl_lib::Pose3DOF_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_lib::Pose3DOF_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 x\n\
float64 y\n\
float64 theta\n\
float64 dt\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hrl_lib::Pose3DOF_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hrl_lib::Pose3DOF_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hrl_lib::Pose3DOF_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_lib::Pose3DOF_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
    stream.next(m.dt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pose3DOF_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrl_lib::Pose3DOF_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hrl_lib::Pose3DOF_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "dt: ";
    Printer<double>::stream(s, indent + "  ", v.dt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HRL_LIB_MESSAGE_POSE3DOF_H

