/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_srvs/srv/FloatArray_Float.srv */
#ifndef HRL_SRVS_SERVICE_FLOATARRAY_FLOAT_H
#define HRL_SRVS_SERVICE_FLOATARRAY_FLOAT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace hrl_srvs
{
template <class ContainerAllocator>
struct FloatArray_FloatRequest_ : public ros::Message
{
  typedef FloatArray_FloatRequest_<ContainerAllocator> Type;

  FloatArray_FloatRequest_()
  : val()
  {
  }

  FloatArray_FloatRequest_(const ContainerAllocator& _alloc)
  : val(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _val_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  val;


  ROS_DEPRECATED uint32_t get_val_size() const { return (uint32_t)val.size(); }
  ROS_DEPRECATED void set_val_size(uint32_t size) { val.resize((size_t)size); }
  ROS_DEPRECATED void get_val_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->val; }
  ROS_DEPRECATED void set_val_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->val = vec; }
private:
  static const char* __s_getDataType_() { return "hrl_srvs/FloatArray_FloatRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "65ac3f59e35977c61c27adccf4c68288"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "dd682166edb796173ec88e7ce3d59245"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64[] val\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, val);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, val);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(val);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct FloatArray_FloatRequest
typedef  ::hrl_srvs::FloatArray_FloatRequest_<std::allocator<void> > FloatArray_FloatRequest;

typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatRequest> FloatArray_FloatRequestPtr;
typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatRequest const> FloatArray_FloatRequestConstPtr;


template <class ContainerAllocator>
struct FloatArray_FloatResponse_ : public ros::Message
{
  typedef FloatArray_FloatResponse_<ContainerAllocator> Type;

  FloatArray_FloatResponse_()
  : val(0.0)
  {
  }

  FloatArray_FloatResponse_(const ContainerAllocator& _alloc)
  : val(0.0)
  {
  }

  typedef double _val_type;
  double val;


private:
  static const char* __s_getDataType_() { return "hrl_srvs/FloatArray_FloatResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "122db3e2ea0d4d63e59164b6bc31deaf"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "dd682166edb796173ec88e7ce3d59245"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 val\n\
\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, val);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, val);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(val);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct FloatArray_FloatResponse
typedef  ::hrl_srvs::FloatArray_FloatResponse_<std::allocator<void> > FloatArray_FloatResponse;

typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatResponse> FloatArray_FloatResponsePtr;
typedef boost::shared_ptr< ::hrl_srvs::FloatArray_FloatResponse const> FloatArray_FloatResponseConstPtr;

struct FloatArray_Float
{

typedef FloatArray_FloatRequest Request;
typedef FloatArray_FloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct FloatArray_Float
} // namespace hrl_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "65ac3f59e35977c61c27adccf4c68288";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x65ac3f59e35977c6ULL;
  static const uint64_t static_value2 = 0x1c27adccf4c68288ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/FloatArray_FloatRequest";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] val\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "122db3e2ea0d4d63e59164b6bc31deaf";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x122db3e2ea0d4d63ULL;
  static const uint64_t static_value2 = 0xe59164b6bc31deafULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/FloatArray_FloatResponse";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 val\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.val);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FloatArray_FloatRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.val);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FloatArray_FloatResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hrl_srvs::FloatArray_Float> {
  static const char* value() 
  {
    return "dd682166edb796173ec88e7ce3d59245";
  }

  static const char* value(const hrl_srvs::FloatArray_Float&) { return value(); } 
};

template<>
struct DataType<hrl_srvs::FloatArray_Float> {
  static const char* value() 
  {
    return "hrl_srvs/FloatArray_Float";
  }

  static const char* value(const hrl_srvs::FloatArray_Float&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dd682166edb796173ec88e7ce3d59245";
  }

  static const char* value(const hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/FloatArray_Float";
  }

  static const char* value(const hrl_srvs::FloatArray_FloatRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dd682166edb796173ec88e7ce3d59245";
  }

  static const char* value(const hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/FloatArray_Float";
  }

  static const char* value(const hrl_srvs::FloatArray_FloatResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HRL_SRVS_SERVICE_FLOATARRAY_FLOAT_H

