/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_srvs/srv/None_Int32.srv */
#ifndef HRL_SRVS_SERVICE_NONE_INT32_H
#define HRL_SRVS_SERVICE_NONE_INT32_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace hrl_srvs
{
template <class ContainerAllocator>
struct None_Int32Request_ : public ros::Message
{
  typedef None_Int32Request_<ContainerAllocator> Type;

  None_Int32Request_()
  {
  }

  None_Int32Request_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "hrl_srvs/None_Int32Request"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "b3087778e93fcd34cc8d65bc54e850d1"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::None_Int32Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::None_Int32Request_<ContainerAllocator>  const> ConstPtr;
}; // struct None_Int32Request
typedef  ::hrl_srvs::None_Int32Request_<std::allocator<void> > None_Int32Request;

typedef boost::shared_ptr< ::hrl_srvs::None_Int32Request> None_Int32RequestPtr;
typedef boost::shared_ptr< ::hrl_srvs::None_Int32Request const> None_Int32RequestConstPtr;


template <class ContainerAllocator>
struct None_Int32Response_ : public ros::Message
{
  typedef None_Int32Response_<ContainerAllocator> Type;

  None_Int32Response_()
  : value(0)
  {
  }

  None_Int32Response_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef int32_t _value_type;
  int32_t value;


private:
  static const char* __s_getDataType_() { return "hrl_srvs/None_Int32Response"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "b3087778e93fcd34cc8d65bc54e850d1"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "b3087778e93fcd34cc8d65bc54e850d1"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 value\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::None_Int32Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::None_Int32Response_<ContainerAllocator>  const> ConstPtr;
}; // struct None_Int32Response
typedef  ::hrl_srvs::None_Int32Response_<std::allocator<void> > None_Int32Response;

typedef boost::shared_ptr< ::hrl_srvs::None_Int32Response> None_Int32ResponsePtr;
typedef boost::shared_ptr< ::hrl_srvs::None_Int32Response const> None_Int32ResponseConstPtr;

struct None_Int32
{

typedef None_Int32Request Request;
typedef None_Int32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct None_Int32
} // namespace hrl_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::None_Int32Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Request_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::None_Int32Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_Int32Request";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::None_Int32Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hrl_srvs::None_Int32Request_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::None_Int32Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Response_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb3087778e93fcd34ULL;
  static const uint64_t static_value2 = 0xcc8d65bc54e850d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::None_Int32Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_Int32Response";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::None_Int32Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 value\n\
\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::None_Int32Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hrl_srvs::None_Int32Response_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::None_Int32Request_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct None_Int32Request_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::None_Int32Response_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct None_Int32Response_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hrl_srvs::None_Int32> {
  static const char* value() 
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const hrl_srvs::None_Int32&) { return value(); } 
};

template<>
struct DataType<hrl_srvs::None_Int32> {
  static const char* value() 
  {
    return "hrl_srvs/None_Int32";
  }

  static const char* value(const hrl_srvs::None_Int32&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::None_Int32Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const hrl_srvs::None_Int32Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::None_Int32Request_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_Int32";
  }

  static const char* value(const hrl_srvs::None_Int32Request_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::None_Int32Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b3087778e93fcd34cc8d65bc54e850d1";
  }

  static const char* value(const hrl_srvs::None_Int32Response_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::None_Int32Response_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_Int32";
  }

  static const char* value(const hrl_srvs::None_Int32Response_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HRL_SRVS_SERVICE_NONE_INT32_H

