/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_srvs/srv/None_FloatArray.srv */
#ifndef HRL_SRVS_SERVICE_NONE_FLOATARRAY_H
#define HRL_SRVS_SERVICE_NONE_FLOATARRAY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace hrl_srvs
{
template <class ContainerAllocator>
struct None_FloatArrayRequest_ : public ros::Message
{
  typedef None_FloatArrayRequest_<ContainerAllocator> Type;

  None_FloatArrayRequest_()
  {
  }

  None_FloatArrayRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "hrl_srvs/None_FloatArrayRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "0db98d790b5b039efb61505385ae8369"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct None_FloatArrayRequest
typedef  ::hrl_srvs::None_FloatArrayRequest_<std::allocator<void> > None_FloatArrayRequest;

typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayRequest> None_FloatArrayRequestPtr;
typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayRequest const> None_FloatArrayRequestConstPtr;


template <class ContainerAllocator>
struct None_FloatArrayResponse_ : public ros::Message
{
  typedef None_FloatArrayResponse_<ContainerAllocator> Type;

  None_FloatArrayResponse_()
  : value()
  {
  }

  None_FloatArrayResponse_(const ContainerAllocator& _alloc)
  : value(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _value_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  value;


  ROS_DEPRECATED uint32_t get_value_size() const { return (uint32_t)value.size(); }
  ROS_DEPRECATED void set_value_size(uint32_t size) { value.resize((size_t)size); }
  ROS_DEPRECATED void get_value_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->value; }
  ROS_DEPRECATED void set_value_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->value = vec; }
private:
  static const char* __s_getDataType_() { return "hrl_srvs/None_FloatArrayResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0db98d790b5b039efb61505385ae8369"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "0db98d790b5b039efb61505385ae8369"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64[] value\n\
\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct None_FloatArrayResponse
typedef  ::hrl_srvs::None_FloatArrayResponse_<std::allocator<void> > None_FloatArrayResponse;

typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayResponse> None_FloatArrayResponsePtr;
typedef boost::shared_ptr< ::hrl_srvs::None_FloatArrayResponse const> None_FloatArrayResponseConstPtr;

struct None_FloatArray
{

typedef None_FloatArrayRequest Request;
typedef None_FloatArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct None_FloatArray
} // namespace hrl_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_FloatArrayRequest";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0db98d790b5b039efb61505385ae8369";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0db98d790b5b039eULL;
  static const uint64_t static_value2 = 0xfb61505385ae8369ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_FloatArrayResponse";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] value\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct None_FloatArrayRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct None_FloatArrayResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hrl_srvs::None_FloatArray> {
  static const char* value() 
  {
    return "0db98d790b5b039efb61505385ae8369";
  }

  static const char* value(const hrl_srvs::None_FloatArray&) { return value(); } 
};

template<>
struct DataType<hrl_srvs::None_FloatArray> {
  static const char* value() 
  {
    return "hrl_srvs/None_FloatArray";
  }

  static const char* value(const hrl_srvs::None_FloatArray&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0db98d790b5b039efb61505385ae8369";
  }

  static const char* value(const hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_FloatArray";
  }

  static const char* value(const hrl_srvs::None_FloatArrayRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0db98d790b5b039efb61505385ae8369";
  }

  static const char* value(const hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_srvs/None_FloatArray";
  }

  static const char* value(const hrl_srvs::None_FloatArrayResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HRL_SRVS_SERVICE_NONE_FLOATARRAY_H

