/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_msgs/msg/FloatArrayBare.msg */
#ifndef HRL_MSGS_MESSAGE_FLOATARRAYBARE_H
#define HRL_MSGS_MESSAGE_FLOATARRAYBARE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace hrl_msgs
{
template <class ContainerAllocator>
struct FloatArrayBare_ : public ros::Message
{
  typedef FloatArrayBare_<ContainerAllocator> Type;

  FloatArrayBare_()
  : data()
  {
  }

  FloatArrayBare_(const ContainerAllocator& _alloc)
  : data(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  data;


  ROS_DEPRECATED uint32_t get_data_size() const { return (uint32_t)data.size(); }
  ROS_DEPRECATED void set_data_size(uint32_t size) { data.resize((size_t)size); }
  ROS_DEPRECATED void get_data_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->data; }
  ROS_DEPRECATED void set_data_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->data = vec; }
private:
  static const char* __s_getDataType_() { return "hrl_msgs/FloatArrayBare"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "788898178a3da2c3718461eecda8f714"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64[] data\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(data);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_msgs::FloatArrayBare_<ContainerAllocator>  const> ConstPtr;
}; // struct FloatArrayBare
typedef  ::hrl_msgs::FloatArrayBare_<std::allocator<void> > FloatArrayBare;

typedef boost::shared_ptr< ::hrl_msgs::FloatArrayBare> FloatArrayBarePtr;
typedef boost::shared_ptr< ::hrl_msgs::FloatArrayBare const> FloatArrayBareConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hrl_msgs::FloatArrayBare_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hrl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> > {
  static const char* value() 
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const  ::hrl_msgs::FloatArrayBare_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_msgs/FloatArrayBare";
  }

  static const char* value(const  ::hrl_msgs::FloatArrayBare_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] data\n\
\n\
\n\
";
  }

  static const char* value(const  ::hrl_msgs::FloatArrayBare_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FloatArrayBare_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrl_msgs::FloatArrayBare_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hrl_msgs::FloatArrayBare_<ContainerAllocator> & v) 
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // HRL_MSGS_MESSAGE_FLOATARRAYBARE_H

