/* Auto-generated by genmsg_cpp for file /home/aellaboudy/aellaboudy_sandbox/gt_packages_new/gt_packages/hrl/hrl_msgs/msg/FloatArray.msg */
#ifndef HRL_MSGS_MESSAGE_FLOATARRAY_H
#define HRL_MSGS_MESSAGE_FLOATARRAY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"

namespace hrl_msgs
{
template <class ContainerAllocator>
struct FloatArray_ : public ros::Message
{
  typedef FloatArray_<ContainerAllocator> Type;

  FloatArray_()
  : header()
  , data()
  {
  }

  FloatArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  data;


  ROS_DEPRECATED uint32_t get_data_size() const { return (uint32_t)data.size(); }
  ROS_DEPRECATED void set_data_size(uint32_t size) { data.resize((size_t)size); }
  ROS_DEPRECATED void get_data_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->data; }
  ROS_DEPRECATED void set_data_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->data = vec; }
private:
  static const char* __s_getDataType_() { return "hrl_msgs/FloatArray"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "fb60495edd59d3fcf90e173153ae8a9a"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
float64[] data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, data);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(data);
    return size;
  }

  typedef boost::shared_ptr< ::hrl_msgs::FloatArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrl_msgs::FloatArray_<ContainerAllocator>  const> ConstPtr;
}; // struct FloatArray
typedef  ::hrl_msgs::FloatArray_<std::allocator<void> > FloatArray;

typedef boost::shared_ptr< ::hrl_msgs::FloatArray> FloatArrayPtr;
typedef boost::shared_ptr< ::hrl_msgs::FloatArray const> FloatArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hrl_msgs::FloatArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hrl_msgs::FloatArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hrl_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::hrl_msgs::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fb60495edd59d3fcf90e173153ae8a9a";
  }

  static const char* value(const  ::hrl_msgs::FloatArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfb60495edd59d3fcULL;
  static const uint64_t static_value2 = 0xf90e173153ae8a9aULL;
};

template<class ContainerAllocator>
struct DataType< ::hrl_msgs::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hrl_msgs/FloatArray";
  }

  static const char* value(const  ::hrl_msgs::FloatArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hrl_msgs::FloatArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64[] data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hrl_msgs::FloatArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hrl_msgs::FloatArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hrl_msgs::FloatArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hrl_msgs::FloatArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FloatArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrl_msgs::FloatArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hrl_msgs::FloatArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // HRL_MSGS_MESSAGE_FLOATARRAY_H

